services:
  postgres:
    image: postgres
    volumes:
      - ./01-base-schema.sql:/docker-entrypoint-initdb.d/01-base-schema.sql
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "15432:5432"
  
  minio:
    image: quay.io/minio/minio
    # environment:
    #   MINIO_ROOT_USER: "admin"
    #   MINIO_ROOT_PASSWORD: "admin"
    volumes:
      - ./minio/data:/data
    ports:
      - "9000:9000"
      - "9090:9090"
    command: server /data --console-address ":9001"