services:
  # dagster:
  #   build: .
  #   env_file: .env
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./minas_data_lab/:/opt/dagster/app/minas_data_lab/
  #     - ./workspace.yaml:/opt/dagster/app/workspace.yaml
  #     - ./dagster.yaml:/opt/dagster/app/dagster.yaml
  # dagster_daemon:
  #   build: .
  #   entrypoint:
  #     - dagster-daemon
  #     - run
  #   container_name: docker_example_daemon
  #   env_file: .env
  #   volumes: # Make docker client accessible so we can launch containers using host docker
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /tmp/io_manager_storage:/tmp/io_manager_storage

  postgres:
    image: postgres
    volumes:
      - ./01-base-schema.sql:/docker-entrypoint-initdb.d/01-base-schema.sql
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
  
  minio:
    image: quay.io/minio/minio
    # environment:
    #   MINIO_ROOT_USER: "admin"
    #   MINIO_ROOT_PASSWORD: "admin"
    volumes:
      - ./minio/data:/data
    ports:
      - "9000:9000"
      - "9090:9090"
      - "9001:9001"
    command: server /data --console-address ":9001"