services:
  postgres:
    image: postgres
    volumes:
      - ./01-setup-local-database.sql:/docker-entrypoint-initdb.d/01-setup-local-database.sql
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
  
  minio:
    image: quay.io/minio/minio
    volumes:
      - ./.minio/data:/data
    ports:
      - "9000:9000"
      - "9090:9090"
      - "9001:9001"
    command: server /data --console-address ":9001"
  
  metabse:
    image: metabase/metabase
    # volumes:
    #   - /home/app/metabase-data:/metabase-data
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - 3000:3000
