dbt_pipelines:
  outputs:
    dev:
      dbname: gov_transparency_hub
      host: localhost
      pass: postgres
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres
  target: dev
