URLS = {
    "tiradentes": "https://ptn.tiradentes.mg.gov.br",
    "saojoaodelrei": "https://ptn.saojoaodelrei.mg.gov.br",
    "saotiago": "https://ptn.saotiago.mg.gov.br",
    "piedadedoriogrande": "https://ptn.piedadedoriogrande.mg.gov.br",
    "cbm": "https://ptn.cbm.mg.gov.br",
    "itutinga": "https://ptn.itutinga.mg.gov.br",
    "carrancas": "https://ptn.carrancas.mg.gov.br",
    "santacruzdeminas": "https://pt.santacruzdeminas.mg.gov.br",
    "ritapolis": "https://pt.ritapolis.mg.gov.br",
    "prados": "https://pt.prados.mg.gov.br",
    "resendecosta": "https://pt.resendecosta.mg.gov.br",
    "nazareno": "https://pt.nazareno.mg.gov.br",
    "madrededeusdeminas": "https://pt.madrededeusdeminas.mg.gov.br",
    "lagoadourada": "https://pt.lagoadourada.mg.gov.br",
    "doresdecampos": "https://pt.doresdecampos.mg.gov.br",
    "coronelxavierchaves": "https://pt.coronelxavierchaves.mg.gov.br",
    "itumirim": "https://pt.itumirim.mg.gov.br",
    "ingai": "https://pt.ingai.mg.gov.br",
    "santabarbaradotugurio": "https://pt.santabarbaradotugurio.mg.gov.br",
    "ressaquinha": "https://pt.ressaquinha.mg.gov.br",
    "ibertioga": "https://pt.ibertioga.mg.gov.br",
    "desterrodeentrerios": "https://pt.desterrodeentrerios.mg.gov.br",
    "carandai": "https://pt.carandai.mg.gov.br",
    "caranaiba": "https://pt.caranaiba.mg.gov.br",
    "barroso": "https://pt.barroso.mg.gov.br",
    "municipioantoniocarlos": "https://pt.municipioantoniocarlos.mg.gov.br",
    "alfredovasconcelos": "https://pt.alfredovasconcelos.mg.gov.br",
    "santanadogarambeu": "http://pt.santanadogarambeu.cam.mg.gov.br",
    "luminarias": "http://pt.luminarias.cam.mg.gov.br",
    "ijaci": "http://transparencia.ijaci.mg.leg.br",
    "capelanova": "http://transparencia.capelanova.mg.leg.br",
}

DETAILED_EXPENSE_FIELDS = [
    "Tipo",
    "Data do Empenho",
    "Liquidação",
    "Pagamento",
    "Unidade",
    "Função",
    "Subfunção",
    "Programa",
    "Projeto Atividade",
    "Categoria Econômica",
    "Fonte de Recurso",
    "CO TCE",
    "CO AUX",
    "Valor",
    "Beneficiário",
    "CPF/CNPJ",
    "Histórico",
]

ITEM_EXPENSE_FIELDS = [
    "Produto",
    "Especificação",
    "Complemento",
    "Unidade",
    "Marca",
    "Quantidade",
    "Valor Unitário",
    "Total"
]

INVOICE_EXPENSE_FIELDS = [
    "Nota Fiscal",
    "Série",
    "Emissão",
    "Vencimento",
    "Chave de Acesso",
]